# Generated by Django 5.1.5 on 2025-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер стола"),
                ),
                (
                    "seats",
                    models.IntegerField(default=4, verbose_name="Количество мест"),
                ),
            ],
        ),
    ]
